
include:
  - project: 'norsktest/dktools'
    file: '/ci-templates/dkbuild.yml'

py35dj18:
  extends: .testpackage
  script:
    - dk testpackage --ci --tag=py35-dj18 --django=1.8.19

coverage:
  dependencies:
    - py35dj18

wheel:
  dependencies:
    - py35dj18
