
include:
  - project: 'norsktest/dktools'
    file: '/ci-templates/dkbuild.yml'

py35dj18:
  extends: .testpackage
  script:
    - dk testpackage --ci --tag=py35-dj18 --django=1.8.19

coverage:
  dependencies:
    - py35dj18

wheel:
  dependencies:
    - py35dj18


deploy_code:
  stage: deploy
  image: thebjorn/dktestpackage3:latest
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DEPLOY_PKEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - dk pkg
    - ssh -v deploy@fischer.datakortet.c.bitbit.net "cd /srv/lib/core/ttcal && git pull"
  environment:
    name: production
    url: https://admin.datakortet.no/userenv/
  when: manual
  only:
    - master
    - pushes
    - web
