language: python

sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"


before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U coverage

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  pytest -v --cov=ttcal tests

after_success:
  codecov
